version: "3.2"
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./docker:/data/docker
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: actinium
      MONGO_INITDB_ROOT_PASSWORD_FILE: /data/docker/mongo.txt
    networks:
      - be
  ui:
    build: ./webapp
    image: webapp:latest
    ports:
      - 3030:3030
    environment:
      PARSE_APP_ID: Actinium
      REST_API_URL: http://api:9000/api
    networks:
      - fe
      - be
  api:
    build: ./adapter
    image: adapter:latest
    ports:
      - 9000:9000
    volumes:
      - ./docker:/usr/src/app/docker
    environment:
      ACTINIUM_ENV_FILE: /usr/src/app/docker/env.json
    networks:
      - fe
      - be
networks:
  fe:
  be:
volumes:
  mongo:
